"""comments table

Revision ID: 442313d6d303
Revises: ff25f0dde8ac
Create Date: 2020-12-09 09:02:21.027335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '442313d6d303'
down_revision = 'ff25f0dde8ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=200), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    # ### end Alembic commands ###
